.TH "cubies" 3 "Thu May 13 2021" "Rubik's Cube EFREI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cubies
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rubiks\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "\fBT_CUBIE_TYPE\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBT_COLOR\fP \fBcolor\fP"
.br
.ti -1c
.RI "\fBT_COLOR\fP \fBcubie_side\fP"
.br
.ti -1c
.RI "\fBneighbour\fP \fBneighbours\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file rubiks\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBT_COLOR\fP color"

.PP
Definition at line 25 of file rubiks\&.h\&.
.SS "\fBT_COLOR\fP cubie_side"

.PP
Definition at line 26 of file rubiks\&.h\&.
.SS "\fBneighbour\fP neighbours[2]"

.PP
Definition at line 27 of file rubiks\&.h\&.
.SS "int num"

.PP
Definition at line 23 of file rubiks\&.h\&.
.SS "\fBT_CUBIE_TYPE\fP type"

.PP
Definition at line 24 of file rubiks\&.h\&.
.SS "int x"

.PP
Definition at line 21 of file rubiks\&.h\&.
.SS "int y"

.PP
Definition at line 22 of file rubiks\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rubik's Cube EFREI from the source code\&.
