.TH "neighbour" 3 "Thu May 13 2021" "Rubik's Cube EFREI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
neighbour
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rubiks\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBT_COLOR\fP \fBnum_side\fP"
.br
.ti -1c
.RI "int \fBnum_cubie\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file rubiks\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int num_cubie"

.PP
Definition at line 17 of file rubiks\&.h\&.
.SS "\fBT_COLOR\fP num_side"

.PP
Definition at line 16 of file rubiks\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rubik's Cube EFREI from the source code\&.
