.TH "rubiks_side" 3 "Thu May 13 2021" "Rubik's Cube EFREI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rubiks_side
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rubiks\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBT_COLOR\fP \fBneighbour_side\fP [4]"
.br
.ti -1c
.RI "\fBT_COLOR\fP \fBopposite_side\fP"
.br
.ti -1c
.RI "\fBT_COLOR\fP \fBside\fP"
.br
.ti -1c
.RI "\fBcubies\fP \fBcubie\fP [9]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file rubiks\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBcubies\fP cubie[9]"

.PP
Definition at line 34 of file rubiks\&.h\&.
.SS "\fBT_COLOR\fP neighbour_side[4]"

.PP
Definition at line 31 of file rubiks\&.h\&.
.SS "\fBT_COLOR\fP opposite_side"

.PP
Definition at line 32 of file rubiks\&.h\&.
.SS "\fBT_COLOR\fP side"

.PP
Definition at line 33 of file rubiks\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rubik's Cube EFREI from the source code\&.
