.TH "draw.h" 3 "Thu May 13 2021" "Rubik's Cube EFREI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
draw.h
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses\&.h>\fP
.br
\fC#include 'rubiks\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRUBIK_LINES\fP   3"
.br
.ti -1c
.RI "#define \fBRUBIK_COLS\fP   4"
.br
.ti -1c
.RI "#define \fBSQ_HEIGHT\fP   4"
.br
.ti -1c
.RI "#define \fBSQ_WIDTH\fP   8"
.br
.ti -1c
.RI "#define \fBSQUARES\fP   ((\fBRUBIK_LINES\fP * 3) * (\fBRUBIK_COLS\fP * 3))"
.br
.ti -1c
.RI "#define \fBMIN_COLORS_NUMBER\fP   256"
.br
.ti -1c
.RI "#define \fBTERM_NOT_BIG_ENOUGH\fP   1"
.br
.ti -1c
.RI "#define \fBTERM_HAS_NO_COLORS\fP   2"
.br
.ti -1c
.RI "#define \fBTERM_HAS_NOT_ENOUGH_COLORS\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcheck_and_set_term\fP (void)"
.br
.ti -1c
.RI "void \fBset_colors\fP (void)"
.br
.ti -1c
.RI "void \fBcreate_board\fP (void)"
.br
.ti -1c
.RI "void \fBdestroy_board\fP (void)"
.br
.ti -1c
.RI "void \fBdetect_resize\fP (__attribute__((unused)) int)"
.br
.ti -1c
.RI "void \fBrubiks_display\fP (\fBrubiks_side\fP *rubiks)"
.br
.ti -1c
.RI "void \fBdraw_rubiks\fP (\fBrubiks_side\fP *rubiks)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "WINDOW * \fBBOARD\fP [\fBSQUARES\fP]"
.br
.ti -1c
.RI "const short \fBBLACK_ON_WHITE\fP"
.br
.ti -1c
.RI "const short \fBBLACK_ON_ORANGE\fP"
.br
.ti -1c
.RI "const short \fBBLACK_ON_GREEN\fP"
.br
.ti -1c
.RI "const short \fBBLACK_ON_RED\fP"
.br
.ti -1c
.RI "const short \fBBLACK_ON_BLUE\fP"
.br
.ti -1c
.RI "const short \fBBLACK_ON_YELLOW\fP"
.br
.ti -1c
.RI "short \fBNB_LINES\fP"
.br
.ti -1c
.RI "short \fBNB_COLS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MIN_COLORS_NUMBER   256"

.PP
Definition at line 23 of file draw\&.h\&.
.SS "#define RUBIK_COLS   4"

.PP
Definition at line 13 of file draw\&.h\&.
.SS "#define RUBIK_LINES   3"

.PP
Definition at line 11 of file draw\&.h\&.
.SS "#define SQ_HEIGHT   4"

.PP
Definition at line 16 of file draw\&.h\&.
.SS "#define SQ_WIDTH   8"

.PP
Definition at line 17 of file draw\&.h\&.
.SS "#define SQUARES   ((\fBRUBIK_LINES\fP * 3) * (\fBRUBIK_COLS\fP * 3))"

.PP
Definition at line 20 of file draw\&.h\&.
.SS "#define TERM_HAS_NO_COLORS   2"

.PP
Definition at line 27 of file draw\&.h\&.
.SS "#define TERM_HAS_NOT_ENOUGH_COLORS   3"

.PP
Definition at line 28 of file draw\&.h\&.
.SS "#define TERM_NOT_BIG_ENOUGH   1"

.PP
Definition at line 26 of file draw\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int check_and_set_term (void)"

.PP
Definition at line 35 of file draw\&.c\&.
.SS "void create_board (void)"

.PP
Definition at line 126 of file draw\&.c\&.
.SS "void destroy_board (void)"

.PP
Definition at line 172 of file draw\&.c\&.
.SS "void detect_resize (__attribute__((unused)) int dummy)"

.PP
Definition at line 19 of file draw\&.c\&.
.SS "void draw_rubiks (\fBrubiks_side\fP * rubiks)"

.PP
Definition at line 205 of file draw\&.c\&.
.SS "void rubiks_display (\fBrubiks_side\fP * rubiks)"

.PP
Definition at line 185 of file draw\&.c\&.
.SS "void set_colors (void)"

.PP
Definition at line 24 of file draw\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const short BLACK_ON_BLUE\fC [extern]\fP"

.PP
Definition at line 13 of file draw\&.c\&.
.SS "const short BLACK_ON_GREEN\fC [extern]\fP"

.PP
Definition at line 11 of file draw\&.c\&.
.SS "const short BLACK_ON_ORANGE\fC [extern]\fP"

.PP
Definition at line 10 of file draw\&.c\&.
.SS "const short BLACK_ON_RED\fC [extern]\fP"

.PP
Definition at line 12 of file draw\&.c\&.
.SS "const short BLACK_ON_WHITE\fC [extern]\fP"

.PP
Definition at line 9 of file draw\&.c\&.
.SS "const short BLACK_ON_YELLOW\fC [extern]\fP"

.PP
Definition at line 14 of file draw\&.c\&.
.SS "WINDOW* BOARD[\fBSQUARES\fP]\fC [extern]\fP"

.PP
Definition at line 8 of file draw\&.c\&.
.SS "short NB_COLS\fC [extern]\fP"

.PP
Definition at line 17 of file draw\&.c\&.
.SS "short NB_LINES\fC [extern]\fP"

.PP
Definition at line 16 of file draw\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Rubik's Cube EFREI from the source code\&.
